shill: Completely exclude ModemInfo when built with USE=-cellular.
Instead of having a shallow implementation of ModemInfo, this CL
completely excludes ModemInfo when building shill without cellular
support. This addresses the following compilation issues when building
shill with USE=-cellular:

modem_info.cc:35:12: error: unused variable 'kCromoService'
modem_info.cc:36:12: error: unused variable 'kCromoPath'
modem_info.cc:38:12: error: unused variable 'kCellularOperatorInfoPath'
mock_modem_info.cc:32: error: undefined reference to shill::ModemInfo::set_pending_activation_store(shill::PendingActivationStore*)'
mock_modem_info.cc:36: error: undefined reference to shill::MockCellularOperatorInfo::MockCellularOperatorInfo()'
mock_modem_info.cc:36: error: undefined reference to shill::ModemInfo::set_cellular_operator_info(shill::CellularOperatorInfo*)'
mock_modem_info.cc:66: error: undefined reference to 'mobile_provider_open_db'

BUG=chromium:329715
TEST=Tested the following with {x86,amd64,arm}-generic:
1. `FEATURES=test emerge-${BOARD} platform2`
2. `USE='-debugd -cellular' emerge-${BOARD} platform2`
3. Run network_3GSmoke test with shill built with cellular support.

Change-Id: I348486604ceaaca5e90dd15df40edeaa6e6b6d68
Reviewed-on: https://chromium-review.googlesource.com/180800
Reviewed-by: Gaurav Shah <gauravsh@chromium.org>
Tested-by: Gaurav Shah <gauravsh@chromium.org>
Commit-Queue: Ben Chan <benchan@chromium.org>
Tested-by: Ben Chan <benchan@chromium.org>