shill: delete unused modem_proxy
This variable is unused leading to errors:
.../shill/cellular_capability_universal_unittest.cc:1717:24: error: unused variable 'modem_proxy' [-Werror=unused-variable]
	mm1::MockModemProxy *modem_proxy = modem_proxy_.get();

BUG=chromium:384185
TEST=pre-cq

Change-Id: Id23e1c2472054344cd2e4fea6d5fff6ccc2c8c68
Reviewed-on: https://chromium-review.googlesource.com/211987
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Ben Chan <benchan@chromium.org>